BEGIN; -- Je lance une suite d'instructions

DROP TABLE IF EXISTS "level",
"answer",
"user",
"quiz",
"question",
"tag",
"quiz_has_tag";

CREATE TABLE IF NOT EXISTS "level" (
  "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,

  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP
);

-- Je crée d'abord la table answser sans la clé étrangère

CREATE TABLE IF NOT EXISTS "answer" (
  "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" TEXT NOT NULL,

  "question_id" INT NOT NULL,

  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "user" (
  "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" TEXT NOT NULL,
  "password" TEXT NOT NULL,
  "firstname" TEXT NULL,
  "lastname" TEXT NULL,

  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "quiz" (
  "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" TEXT NOT NULL,
  "description" TEXT NULL,
  "user_id" INT NOT NULL REFERENCES "user"("id"), -- Je peux utiliser directement REFERENCES ici pour indiqué une clef étrangère (forme raccourci)

  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP

  -- CONSTRAINT fk_author FOREIGN KEY ("user_id") REFERENCES "user"("id")
);

CREATE TABLE IF NOT EXISTS "question" (
  "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "question" TEXT NOT NULL,
  "anecdote" TEXT NOT NULL,
  "wiki" TEXT NULL,
  
  "quiz_id" INT NOT NULL REFERENCES "quiz"("id"),
  "level_id" INT NOT NULL REFERENCES "level"("id"),
  "answer_id" INT NOT NULL,

  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP,
  
  CONSTRAINT fk_correctAnswer FOREIGN KEY ("answer_id") REFERENCES "answer"("id")
);


CREATE TABLE IF NOT EXISTS "tag" (
  "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,

  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "quiz_has_tag" (
  "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "quiz_id" INT NOT NULL REFERENCES "quiz"("id"),
  "tag_id" INT NOT NULL REFERENCES "tag"("id"),
  
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP,

  UNIQUE("quiz_id", "tag_id") -- Les combinaisons quiz_id & tag_id doivent être unique
);
-- Une fois que la table answer et question sont crée ... a ce moment là je vais pouvoir
-- **MODIFIER/ALTERER** la table answer pour mettre la clé étrangère
ALTER TABLE "answer" 
  ADD FOREIGN KEY ("question_id") REFERENCES "question"("id");


COMMIT; -- Une fois que tout est prêt, j'applique les changements